import {
  changePassword,
  clearAuthTokens,
  deleteAccount,
  getAccessToken,
  getCurrentUser,
  getRefreshToken,
  login,
  logout,
  refreshAccessToken,
  requestPasswordReset,
  resendVerificationEmail,
  resetPassword,
  setAccessToken,
  setRefreshToken,
  signup,
  updateProfile,
  uploadProfileImage,
  verifyEmail,
  type LoginResponse,
  type SignupData,
} from "@/lib/auth";

export {
  login,
  signup,
  verifyEmail,
  requestPasswordReset,
  resendVerificationEmail,
  resetPassword,
  refreshAccessToken,
  logout,
  getCurrentUser,
  updateProfile,
  changePassword,
  uploadProfileImage,
  deleteAccount,
  setAccessToken,
  getAccessToken,
  setRefreshToken,
  getRefreshToken,
  clearAuthTokens,
};

export type { LoginResponse, SignupData };

export const authService = {
  login,
  signup,
  verifyEmail,
  requestPasswordReset,
  resendVerificationEmail,
  resetPassword,
  refreshAccessToken,
  logout,
  getCurrentUser,
  updateProfile,
  changePassword,
  uploadProfileImage,
  deleteAccount,
  setAccessToken,
  getAccessToken,
  setRefreshToken,
  getRefreshToken,
  clearAuthTokens,
};
