import {
  checkAvailability,
  createProperty,
  deleteProperty,
  getPropertyHostContact,
  getHostOwnProperties,
  getProperties,
  getPropertyById,
  getUnavailableDates,
  updateProperty,
  uploadPropertyImages,
  type AvailabilityResponse,
  type DeletePropertyResponse,
  type GetPropertiesParams,
  type PropertiesResponse,
  type Property,
  type PropertyHostContact,
  type PropertyHostContactResponse,
  type PropertyResponse,
  type UnavailableDateRange,
  type UnavailableDatesResponse,
  type UploadPropertyImagesResponse,
} from "@/lib/propertyApi";

export {
  getProperties,
  getHostOwnProperties,
  getPropertyById,
  getPropertyHostContact,
  checkAvailability,
  getUnavailableDates,
  createProperty,
  updateProperty,
  deleteProperty,
  uploadPropertyImages,
};

export type {
  Property,
  PropertyHostContact,
  PropertyHostContactResponse,
  PropertyResponse,
  PropertiesResponse,
  AvailabilityResponse,
  UnavailableDateRange,
  UnavailableDatesResponse,
  GetPropertiesParams,
  DeletePropertyResponse,
  UploadPropertyImagesResponse,
};

export const propertyService = {
  getProperties,
  getPropertyById,
  getPropertyHostContact,
  checkAvailability,
  getUnavailableDates,
  createProperty,
  updateProperty,
  deleteProperty,
  uploadPropertyImages,
};
